<?php

namespace ContainerUdmXLxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GBllMQIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GBllMQI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GBllMQI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'man' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'man' => '?',
        ]);
    }
}
