<?php

namespace ContainerTTpBoXM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DbiRyJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dbiRyJ_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dbiRyJ_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filesystem' => ['privates', 'filesystem', 'getFilesystemService', true],
            'repo' => ['privates', 'App\\Repository\\FormationRepository', 'getFormationRepositoryService', true],
        ], [
            'filesystem' => '?',
            'repo' => 'App\\Repository\\FormationRepository',
        ]);
    }
}
