<?php

namespace ContainerOoToTGw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LTGdZi7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LTGdZi7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LTGdZi7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filesystem' => ['privates', 'filesystem', 'getFilesystemService', true],
            'repo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'filesystem' => '?',
            'repo' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
