<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOoToTGw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOoToTGw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOoToTGw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOoToTGw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOoToTGw\App_KernelDevDebugContainer([
    'container.build_hash' => 'OoToTGw',
    'container.build_id' => 'a8a23d51',
    'container.build_time' => 1701968960,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOoToTGw');
