<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWrRS6bX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWrRS6bX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWrRS6bX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWrRS6bX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWrRS6bX\App_KernelDevDebugContainer([
    'container.build_hash' => 'WrRS6bX',
    'container.build_id' => '7cd6437d',
    'container.build_time' => 1701779088,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWrRS6bX');
