<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Avh9yj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Avh9yj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Avh9yj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Avh9yj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0Avh9yj\App_KernelDevDebugContainer([
    'container.build_hash' => '0Avh9yj',
    'container.build_id' => '2656bedf',
    'container.build_time' => 1700924629,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Avh9yj');
